version: '3.7'
services:
  wp:
    container_name: wp-apac
    image: wordpress:latest
    ports:
     - '80:80'
    volumes:
       - './wp-data:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: WP123
      WORDPRESS_DB_NAME: wp
     
  db:
    image: mysql:5.7
    container_name: dibbi-wp
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: db
      MYSQL_USER : myuser
      MYSQL_PASSWORD: WP123

  eagleeye:
    container_name: eagleeye
    image: phpmyadmin:5.1.1
    ports:
      - '8817:80'
    environment:
     PMA_HOST: db
     MYSQL_USER : myuser
     MYSQL_PASSWORD: WP123

volumes:
  db_data: {}








